// build.js — generates config/config.js from Vercel environment variables
const fs = require("fs");

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_ANON_KEY;

if (!url || !key) {
  console.error("ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set.");
  process.exit(1);
}

const content = `// Auto-generated by build.js — do not edit manually
const CONFIG = {
  supabase: {
    url: "${url}",
    anonKey: "${key}"
  }
};
`;

fs.writeFileSync("config/config.js", content);
console.log("config/config.js generated successfully.");
