// Auto-generated by build.js — do not edit manually
// For local dev: run `node build.js` with env vars set, or fill in values below
const CONFIG = {
  supabase: {
    url: "",
    anonKey: ""
  }
};
